name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # Using Node 18 for better ESM support

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install dependencies
        run: |
          npm ci
          npm install --save-dev @eslint/js eslint eslint-plugin-react-hooks eslint-plugin-react-refresh typescript-eslint
          npm ls @eslint/js eslint eslint-plugin-react-hooks eslint-plugin-react-refresh typescript-eslint || echo "Some dependencies may still be missing!"

      - name: Debug Module Resolution
        run: |
          ls -la node_modules/@eslint/js || echo "@eslint/js not found"
          node --no-warnings -e "import('@eslint/js').then(() => console.log('@eslint/js found')).catch(err => console.error(err))"

  lint-and-test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies in lint-and-test job
        run: npm ci

      - name: Run ${{ matrix.task }}
        run: |
          if [ "${{ matrix.task }}" = "lint" ]; then
            # Directly invoke the locally installed ESLint binary.
            ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx --config ./eslint.config.js;
          else
            npx jest --config=jest.config.js --ci --coverage || echo "Tests failed!";
          fi

  upload-coverage:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Coverage to Codecov
        run: |
          curl -s https://codecov.io/bash | bash

  audit:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run npm audit
        run: npm audit --production
